import pandas as pd

from uuid import UUID, uuid4
from pydantic import BaseModel, Field

from models.base import BookItem


class Book(BaseModel):
    """
    A book object.

    Args:
        title (str): The title of the book.
    """
    title: str


class Paragraphs(BookItem):
    """
    A paragraphs item object.

    Args:
        page (int): The page number of the chapter.
        content (list[str]): The list of paragraphs.
    """
    content: list[str]


class List(BookItem):
    """
    A list item object.

    Args:
        page (int): The page number of the chapter.
        title (str): The title of the list.
        type (str): The type of the list. Defaults to "unordered".
        content (list[str | dict[str, str]]): The list of items.
    """
    page: int
    title: str = None
    type: str = None
    content: list[str | dict[str, str]] | dict[str, str]


class Table(BookItem):
    """
    A table item object.

    Args:
        id (UUID): The ID of the chapter item. Defaults to an autogenerated UUID.
        parent_id (UUID): The ID of the parent chapter.
        book_id (UUID): The ID of the book.
        chapter_id (UUID): The ID of the chapter.
        page (int): The page number of the chapter.
        title (str): The title of the table.
        type (str): The type of the table. Defaults to "table".
        metadata (dict[str, str]): The metadata of the table.
        content (pd.DataFrame): The content of the table.
    """
    title: str = None
    type: str = None
    metadata: dict[str, str] = None
    content: dict
